# frozen_string_literal: true

source "http://rubygems.org"

gem 'capybara', '3.39.2'                 
gem 'cucumber', '5.3.0'
gem 'report_builder', '1.9'
gem 'json_matchers'
gem 'wait_until'
gem 'rspec'
gem 'pry'
gem 'site_prism'
gem 'webdrivers', '5.3.1'
gem 'rexml'
gem 'dbi'
gem 'rails'
gem 'execjs'
#gem 'date'
#gem 'ruby-oci8'
gem 'sequel'
gem 'capybara-screenshot'
gem 'rubyzip', '~> 2.3.0'
gem 'ruby_docx', '0.0.4'
gem 'date', '~> 3.2.2'
gem 'activesupport', '~> 6.1' 


