name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install dependencies
      run: |
        cd front  # Muda para o diretório 'front'
        bundle install  # Instala as dependências do bundle
    - name: Run tests
      run: |
        cd front  # Garante que está no diretório correto
        bundle exec cucumber  # Executa os testes
