name: B3 - UAT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser  # Tenta instalar via apt-get
          sudo snap install chromium  # Alternativa para instalar via snap se o apt-get falhar
          cd front  # Navega para o diretório 'front' onde o Gemfile está localizado
          gem install rails  # Certifique-se de instalar o Rails antes de rodar o bundle
          bundle install  # Instala as dependências do Gemfile, incluindo Rails

      - name: Check Chromium version
        run: |
          chromium-browser --version  # Verifica a versão do Chromium instalada

      - name: Run Tests
        run: |
          cd front  # Certifica-se de estar no diretório 'front' para rodar os testes
          bundle exec cucumber  # Executa os testes
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMIUM_FLAGS: "--headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222"








