name: B3 - UAT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Ruby (version 2.7.0 or higher)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'  # Garantir que a versão seja >= 2.7.0

      - name: Update RubyGems to avoid version issues
        run: gem update --system 3.2.3  # Atualizando RubyGems

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          cd front  # Muda para o diretório 'front' onde o Gemfile está localizado
          bundle install  # Instala as dependências do Gemfile

      - name: Run Tests
        run: |
          cd front  # Certifica-se de estar no diretório 'front' para rodar os testes
          bundle exec cucumber  # Executa os testes
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser




